format = """
$time\
$username\
$hostname\
$kubernetes\
${custom.git_host}\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$lua\
$line_break\
${custom.diskfree}\
$directory\
$jobs\
$character"""

right_format="""
$cmd_duration\
$line_break"""

continuation_prompt = "▶"

scan_timeout = 10

add_newline = true

[custom.diskfree]
#command = "df -h .|tail -1|awk '{print \"(\" $4 \")\"}'"
command = "echo \"(\"`df -h .|tail -1|sed -E 's/ +/_/g' |cut -d'_' -f4`\")\""

format = "[$output ]($style)"
when = true

[time]
disabled = false
style = "bold #80ff00"
format = '[\[$time\]]($style) '
time_format = '%T'
utc_time_offset = '-3'

[battery]
disabled = true

[character]
success_symbol = "[\uf054](bright-green)"
error_symbol = "[\uf467](bright-red)"

[cmd_duration]
show_notifications = false
min_time_to_notify = 60_000

[directory]
truncation_length = 5
truncate_to_repo=false
format = "[](blue) [$path ]($style)[$read_only]($read_only_style)"
read_only = " "
truncation_symbol = "..."
fish_style_pwd_dir_length = 0

[git_branch]
format = ":[$symbol$branch]($style)"
symbol = " "

[git_state]
format = '\(:[$state( $progress_current/$progress_total)]($style)\)'

[git_status]
format = '(:[$all_status$ahead_behind]($style)) '
conflicted = '\[ [$count](bright-white bold)\]'
ahead = '\[[﯁ ](bright-blue)[$count](bright-white bold)\]'
behind = '\[[﮾ ](white)[$count](bright-white bold)\]'
diverged = '\[[ ](purple)|[ ﯁ ](bright-blue)[$ahead_count](bright-white bold)[ ﮾ ](white)[$behind_count](bright-white)\]'
untracked = '\[ [$count](bright-white bold)\]'
stashed = '\[[](yellow) [$count](bright-white bold)\]'
modified = '\[[ ](bright-yellow)[$count](bright-white bold)\]'
staged = '\[[ ](bright-green)[$count](bright-white bold)\]'
renamed = '\[[ ](bright-cyan) [$count](bright-white bold)\]'
deleted = '\[ [$count](bright-white bold)\]'

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[custom.git_host]
command = """
URL=$(command git ls-remote --get-url 2> /dev/null)

if [[ "$URL" =~ "github" ]]; then
    ICON=" "
elif [[ "$URL" =~ "gitlab" ]]; then
    ICON=" "
elif [[ "$URL" =~ "bitbucket" ]];then
    ICON=" "
elif [[ "$URL" =~ "kernel" ]];then
    ICON=" "
elif [[ "$URL" =~ "archlinux" ]];then
    ICON=" "
elif [[ "$URL" =~ "gnu" ]];then
    ICON=" "
elif [[ "$URL" =~ "git" ]];then
    ICON=" "
else
    ICON=" "
    URL="localhost"
fi

for PATTERN in "https" "http" "git" "://" "@"; do
    [[ "$URL" == "$PATTERN"* ]] && URL="${URL##$PATTERN}"
done

for PATTERN in "/" ".git"; do
    [[ "$URL" == *"$PATTERN" ]] && URL="${URL%%$PATTERN}"
done
printf "%s%s" "$ICON" "$URL"
"""
directories = [".git"]
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
shell = ["bash","--norc","--noprofile"]
style = "bright-yellow bold"
format = " at [$output]($style)"

[hostname]
ssh_only = false
format = '@[$hostname](bold #80ff00) '
trim_at = '.companyname.com'
disabled = false

[username]
style_user = 'bold #80ff00'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true
